package com.altmedia.billboard.entity;

import java.util.Date;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName = "Bid")
public abstract class Bid {
	private String id;
	private String listingId;
	private String specialInstruction;
	private int priority;
	private UserInfo userInfo;
	private String createdById;
	private String modifiedById;
	private Date createdDate;
	private Date modifiedDate;

	@DynamoDBHashKey(attributeName = "Id")
	@DynamoDBAutoGeneratedKey
	public String getId() {
		return id;
	}

	public Bid setId(String id) {
		this.id = id;
		return this;
	}

	@DynamoDBAttribute(attributeName = "ListingId")
	public String getListingId() {
		return listingId;
	}

	@DynamoDBAttribute(attributeName = "SpecialInstruction")
	public String getSpecialInstruction() {
		return specialInstruction;
	}

	public Bid setListingId(String listingId) {
		this.listingId = listingId;
		return this;
	}

	public Bid setSpecialInstructions(String specialInstruction) {
		this.specialInstruction = specialInstruction;
		return this;
	}

	public Bid setPriority(int priority) {
		this.priority = priority;
		return this;
	}

	@DynamoDBAttribute(attributeName = "Priority")
	public int getPriority() {
		return priority;
	}

	@DynamoDBAttribute(attributeName = "ModifiedById")
	public String getModifiedById() {
		return modifiedById;
	}

	@DynamoDBAttribute(attributeName = "CreatedDate")
	public Date getCreatedDate() {
		return createdDate;
	}

	@DynamoDBAttribute(attributeName = "ModifiedDate")
	public Date getModifiedDate() {
		return modifiedDate;
	}

	public Bid setModifiedById(String modifiedById) {
		this.modifiedById = modifiedById;
		return this;
	}

	public Bid setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
		return this;
	}

	public Bid setModifiedDate(Date modifiedDate) {
		this.modifiedDate = modifiedDate;
		return this;
	}

	@DynamoDBAttribute(attributeName = "UserInfo")
	public UserInfo getUserInfo() {
		return userInfo;
	}

	public Bid setUserInfo(UserInfo userInfo) {
		this.userInfo = userInfo;
		return this;
	}

	@DynamoDBAttribute(attributeName = "CreatedById")
	public String getCreatedById() {
		return createdById;
	}

	public Bid setCreatedById(String createdById) {
		this.createdById = createdById;
		return this;
	}

}
