package com.altmedia.billboard.entity;

import java.util.Date;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName = "Listing")
public abstract class Listing {
	private String billBoardId;
	private String id;
	private Date fromDate;
	private Date toDate;
	private int minimumPeriod;
	private int pricePerMonth;
	private String createdById;
	private String modifiedById;
	private Date createdDate;
	private Date modifiedDate;

	// Partition key
	@DynamoDBHashKey(attributeName = "Id")
	@DynamoDBAutoGeneratedKey
	public String getId() {
		return id;
	}

	@DynamoDBAttribute(attributeName = "BillBoardId")
	public String getBillBoardId() {
		return billBoardId;
	}

	@DynamoDBAttribute(attributeName = "FromDate")
	Date getFromDate() {
		return fromDate;
	}

	@DynamoDBAttribute(attributeName = "ToDate")
	public Date getToDate() {
		return toDate;
	}

	@DynamoDBAttribute(attributeName = "MinimumPeriod")
	public int getMinimumPeriod() {
		return minimumPeriod;
	}

	@DynamoDBAttribute(attributeName = "PricePerMonth")
	public int getPricePerMonth() {
		return pricePerMonth;
	}

	@DynamoDBAttribute(attributeName = "CreatedById")
	public String getCreatedById() {
		return createdById;
	}

	@DynamoDBAttribute(attributeName = "ModifiedById")
	public String getModifiedById() {
		return modifiedById;
	}

	@DynamoDBAttribute(attributeName = "CreatedDate")
	public Date getCreatedDate() {
		return createdDate;
	}

	@DynamoDBAttribute(attributeName = "ModifiedDate")
	public Date getModifiedDate() {
		return modifiedDate;
	}

	public Listing setId(String id) {
		this.id = id;
		return this;
	}

	public Listing setFromDate(Date fromDate) {
		this.fromDate = fromDate;
		return this;
	}

	public Listing setToDate(Date toDate) {
		this.toDate = toDate;
		return this;
	}

	public Listing setMinimumPeriod(int minimumPeriod) {
		this.minimumPeriod = minimumPeriod;
		return this;
	}

	public Listing setPricePerMonth(int pricePerMonth) {
		this.pricePerMonth = pricePerMonth;
		return this;
	}

	public Listing setCreatedById(String createdById) {
		this.createdById = createdById;
		return this;
	}

	public Listing setModifiedById(String modifiedById) {
		this.modifiedById = modifiedById;
		return this;
	}

	public Listing setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
		return this;
	}

	public Listing setModifiedDate(Date modifiedDate) {
		this.modifiedDate = modifiedDate;
		return this;
	}

	public Listing setBillBoardId(String billBoardId) {
		this.billBoardId = billBoardId;
		return this;
	}
}
